######################### NOTE #########################
# // bchang01 - first input is what to read, second input is what to write to
######################### NOTE #########################

import os
import sys

width = 0
file_path = os.path.abspath(__file__)
file_to_read = ""
file_to_read_name = ""
file_to_write = ""
file_to_write_name = ""
counter = 0

if len(sys.argv) == 2 or len(sys.argv) == 3:
    print("Received input trace: " + sys.argv[1])
    file_to_read = sys.argv[1]
    file_to_read_name = sys.argv[1].split(".")[0]

    if (len(sys.argv) == 3):
        print("Received output: " + sys.argv[2])
        file_to_write_name = sys.argv[2].split(".")[0]
        file_to_write = file_to_write_name + ".sv"
    else: 
        print("Using input file name to write a new file")
        file_to_write_name = file_to_read_name
        file_to_write = file_to_read_name + ".sv"    
else:
    print("Usage: rom_gen.py <input_trace_file> <[optional]output_trace_file_name>.sv")
    print("       - if no output file name given, will use the trace file's name")
    sys.exit(1)


print("Generating ROM")
write_file = open(file_to_write, "w")
read_file = open(file_to_read, "r")

write_file.write("// AUTOGENERATED FILE FROM rom_gen.py <input file> <output file>.sv\n")
write_file.write("// Ensure your addr range and data ranges are good and connected from the tb\n")
write_file.write("module " + file_to_write_name + " #(addr_width = 30, data_width = 80) (\n")
write_file.write("    input logic [addr_width - 1 : 0] addr_i,\n")
write_file.write("    output logic [data_width - 1 : 0] data_o\n")
write_file.write(");\n")

write_file.write("    always_comb case(addr_i)\n")
input_lines = read_file.readlines()
for line in input_lines:
    if ("#" not in line) and ("//" not in line) and ("\n" not in line[0]):
        write_file.write("        " + str(counter) + ": data_o = " + line.replace("\n", "") + ";\n")
        counter += 1
    else:
        write_file.write("        //" + line)

write_file.write("        default: data_o = 'X;\n")
write_file.write("    endcase\n")
write_file.write("endmodule // " + file_to_write_name)

write_file.close();
read_file.close();

print("Done")
